server:
  port: 8443
  ssl:
    key-store-type: pkcs12
    key-alias: tomcat
    enabled: true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000

    show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.type: debug
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 5
  file:
    name:

